import type { Metadata } from "next";
import styles from "./global.module.scss";
import HeaderPanel from "@/components/HeaderPanel/";
import FooterPanel from "@/components/FooterPanel";

export const metadata: Metadata = {
  title: "Matthew Dalby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={styles['main']}>
        <HeaderPanel />
        <div className={styles['main2_']}>
          {children}
        </div>
        <div className={styles['footer']}>
          <FooterPanel />
        </div>
      </body>
    </html>
  );
}
