import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import styles from "./global.module.scss";
import HeaderPanel from "@/components/HeaderPanel/";
import FooterPanel from "@/components/FooterPanel";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-be-vietnam-pro",
});

export const metadata: Metadata = {
  title: "Matthew Dalby",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={beVietnamPro.variable}>
      <body className={styles['main']}>
        <HeaderPanel />
        <div className={styles['main2_']}>
          {children}
        </div>
        <div className={styles['footer']}>
          <FooterPanel />
        </div>
      </body>
    </html>
  );
}
